version: "2"
services:
  nginx:
    image: nginx:latest
    container_name: ngx01
    ports:
      - "80:80"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./EKUCourseMonitorWebpage/static:/static
    depends_on:
      - web
  web:
    build: .
    container_name: dg01
    command: "/bin/bash /run/setup.sh"
    depends_on:
      - db
    volumes:
      - ./EKUCourseMonitorWebpage:/src
    expose:
      - "8000"
  db:
    image: postgres:latest
    container_name: ps01
