version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: ngx01
    restart: always
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - static:/static
      - ./certbot/certs:/certs
      - ./certbot/cert_params:/cert_params
    depends_on:
      - web
  web:
    build: .
    container_name: dg01
    command: "/bin/bash /run/run.sh"
    restart: always
    depends_on:
      - db
    volumes:
      - static:/static
    expose:
      - "8000"
  db:
    image: postgres:latest
    container_name: ps01
    restart: always
volumes:
  static: