# Generated by Django 2.1.4 on 2019-01-01 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_auto_20190101_0357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='deactivated',
        ),
        migrations.RemoveField(
            model_name='email',
            name='deactivation_code',
        ),
    ]
