# Generated by Django 2.1.4 on 2019-01-01 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_auto_20180818_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_monitored',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='thread_active',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='email',
            name='deactivated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='email',
            name='deactivation_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='welcomed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.PositiveSmallIntegerField(choices=[(2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019)], default=2019),
        ),
    ]
