#!/bin/bash

NAME="EKUCourseMonitorWebpage"
DIR=/src
USER=root
GROUP=root
WORKERS=3
BIND=0.0.0.0:8000
DJANGO_SETTINGS_MODULE=EKUCourseMonitorWebpage.settings
DJANGO_WSGI_MODULE=EKUCourseMonitorWebpage.wsgi
LOG_LEVEL=error

cd $DIR

export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DIR:$PYTHONPATH

exec gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $WORKERS \
  --user=$USER \
  --group=$GROUP \
  --bind=$BIND \
  --log-level=$LOG_LEVEL \
  --log-file=-